### PR TITLE
fix: reset state on load

### LINKED ISSUE #41: TextTrackButton isn't reset when loading a new manifest
This issue is confirmed for Shaka when loading HLS stream: 

https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8 

**followed by** MPEG-DASH stream: 

https://f53accc45b7aded64ed8085068f31881.egress.mediapackage-vod.eu-north-1.amazonaws.com/out/v1/1c63bf88e2664639a6c293b4d055e6bb/64651f16da554640930b7ce2cd9f758b/66d211307b7d43d3bd515a3bfb654e1c/manifest.mpd

The same subtitle languages + "Shaka Player TextTrack" show up, even though none are available.

### PR DESCRIPTION
**Pull request by slowmove**
fixes #41

### CODE REVIEW

File: packages/core/src/tech/BaseTech.ts [hunk 1]
```diff
@@ -365,6 +366,14 @@ export default class BaseTech extends EventEmitter {
...
     this.updateState({
       playbackState: PlaybackState.LOADING,
+      currentTime: 0,
+      duration: 0,
+      isLive: false,
+      isAtLiveEdge: false,
+      isSeekable: true,
+      isMuted: this.video.muted,
+      audioTracks: [],
+      textTracks: [],
```
Comment (birme) [inline packages/core/src/tech/BaseTech.ts:376]: I think a `volume` is missing here (as it has been recently added)

**Review by birme — APPROVED** [review]
Looked good from the backseat
